version: '3.8'

services:
  daemon-api:
    build: .
    ports:
      - "${PORT:-8004}:${PORT:-8004}"
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - DATABASE_URL=sqlite:///./data/daemon.db
      - BACKUP_DIR=./backups
      - HOST=0.0.0.0
      - PORT=${PORT:-8004}
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-8004}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - daemon-api
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  daemon_data:
  daemon_backups:
