name: daemon

services:
  api:
    build: .
    ports:
      - "${PORT:-8004}:${PORT:-8004}"
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - DATABASE_URL=sqlite:///./data/daemon.db
      - BACKUP_DIR=./backups
      - HOST=0.0.0.0
      - PORT=${PORT:-8004}
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-8004}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Frontend server (development)
  frontend-dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-8005}:${FRONTEND_PORT:-8005}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-8005}
      - DAEMON_API_URL=http://api:${PORT:-8004}
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - frontend-dev

  # Frontend server (production with nginx + SSL)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DAEMON_API_URL=http://api:${PORT:-8004}
    # Only mount external SSL certificates if the ssl directory exists
    # For testing, the container uses self-signed certificates built in the Dockerfile
    # volumes:
    #   - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - frontend

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  daemon_data:
  daemon_backups:
