name: Code Formatting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write

jobs:
  format:
    name: Auto-format Code
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Format code with Black
        run: black app/ tests/

      - name: Sort imports with isort
        run: isort app/ tests/

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatting changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: auto-format code with Black and isort"
          git push

  format-pr:
    name: Format PR Code
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

  check-format:
    name: Check Code Format
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check Black formatting
        run: black --check --diff app/ tests/

      - name: Check isort formatting
        run: isort --check-only --diff app/ tests/

      - name: Comment on PR if formatting needed
        if: failure()
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🎨 Code Formatting Required

              This PR requires code formatting. Please run:

              \`\`\`bash
              black app/ tests/
              isort app/ tests/
              \`\`\`

              Or enable auto-formatting in your IDE.`
            });
